
DROP TABLE IF EXISTS RESOURCE;
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS GRAPH_CONFIG_OPTION_DICTIONARY;

CREATE TABLE RESOURCE (
  ID          INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME        VARCHAR(255) NOT NULL UNIQUE
  COMMENT '资源的中文名字，如角色',
  CODE        VARCHAR(255) NOT NULL UNIQUE
  COMMENT '资源的英文名字，如role，用来进行shiro',
  DESCRIPTION VARCHAR(255)
)
  CHARSET = utf8;

#资源初始化
INSERT INTO RESOURCE (ID, NAME, CODE) VALUES
  (1, '用户', 'user'),
  (2, '资源', 'resource'),
  (3, '权限', 'permission'),
  (4, '角色', 'role'),
  (5, '菜单', 'menu'),
  (6, '业务线', 'businessLine'),
  (7, '图配置', 'graphConfiguration'),
  (8, '图建模', 'graphSchema'),
  (9, '图数据', 'graphData'),
  (10, '图查询', 'graphVisualization'),
  (11, '图算法', 'graphAlgorithm'),
  (12, '图项目', 'project'),
  (13, '图配置项', 'graphConfigDictionary'),
  (14, '系统管理', 'systemManager'),
  (15, '我的工作台', 'myDesk');

#用户
CREATE TABLE USER (
  ID           INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ERP          VARCHAR(128) NOT NULL UNIQUE,
  USERNAME     VARCHAR(128) NOT NULL,
  ORGANIZATION VARCHAR(128) COMMENT '用户所属的组织自机构，用来按照业务线为粒度进行权限控制',
  IS_ENABLED   BOOLEAN      NOT NULL DEFAULT TRUE #账户是否启用
)
  CHARSET = utf8;

INSERT INTO USER (ID, ERP, USERNAME, ORGANIZATION) VALUES
  (1, 'bjliufangqi', '刘方琦', '小米科技-技术研发部-数据部'),
  (2, 'bjluzhou', '卢周', '小米科技-技术研发部-数据部-图计算平台部'),
  (3, 'qianyong11', '钱勇', '小米科技-技术研发部-数据部-图计算平台部'),
  (4, 'xiangzuqi1', '项祖琪', '小米科技-技术研发部-数据部-图计算平台部'),
  (5, 'haotong3', '郝彤', '小米科技-技术研发部-数据部-图计算平台部'),
  (6, 'zhangwenjun26', '张文军', '小米科技-技术研发部-数据部-图计算平台部'),
  (7, 'yuhui1', '余辉', '小米科技-技术研发部-数据部-图计算平台部'),
  (8, 'zhouliang47', '周亮', '小米科技-技术研发部-数据部-图计算平台部'),
  (9, 'duqiang3', '杜强', '小米科技-供应链金融部-信用与风险管理部-决策引擎部'),
  (10, 'liuchangsheng3', '刘昌盛','小米科技-技术研发部-数据部-创新研发部-产品运营组'),
  (11, 'fanyeliang', '范叶亮','小米科技-技术研发部-数据部-图计算平台部');


#图数据库配置项字典表
CREATE TABLE GRAPH_CONFIG_OPTION_DICTIONARY (
  ID            INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
  GROUP_KEY     VARCHAR(255),
  NAME          VARCHAR(255) NOT NULL UNIQUE,
  UNIQUE `GROUP_KEY_NAME_UNIQUE_IDX` (GROUP_KEY(100), NAME(100)),
  DATA_TYPE     VARCHAR(255) NOT NULL,
  DEFAULT_VALUE VARCHAR(255),
  MUTABILITY    VARCHAR(255) NOT NULL,
  DESCRIPTION   TEXT
)
  CHARSET = utf8;

INSERT INTO GRAPH_CONFIG_OPTION_DICTIONARY (ID, GROUP_KEY, NAME, DESCRIPTION, DATA_TYPE, DEFAULT_VALUE, MUTABILITY)
VALUES (1, 'cache', 'cache.db-cache',
        'Whether to enable JanusGraph’s database-level cache, which is shared across all transactions. Enabling this option speeds up traversals by holding hot graph elements in memory, but also increases the likelihood of reading stale data. Disabling it forces each transaction to independently fetch graph elements from storage before reading/writing them.',
        'Boolean', 'false', 'MASKABLE'),
  (2, 'cache', 'cache.db-cache-clean-wait', 'How long, in milliseconds, database-level cache will keep entries after flushing them. This option i', 'Integer', '50', 'GLOBAL_OFFLINE'),
  (3, 'cache', 'cache.db-cache-size', 'Size of JanusGraph’s database level cache. Values between 0 and 1 are interpreted as a percentage of', 'Double', '0.3', 'MASKABLE'),
  (4, 'cache', 'cache.db-cache-time', 'Default expiration time, in milliseconds, for entries in the database-level cache. Entries are evict', 'Long', '10000', 'GLOBAL_OFFLINE'),
  (5, 'cache', 'cache.tx-cache-size', 'Maximum size of the transaction-level cache of recently-used vertices.', 'Integer', '20000', 'MASKABLE'),
  (6, 'cache', 'cache.tx-dirty-size', 'Initial size of the transaction-level cache of uncommitted dirty vertices. This is a performance hin', 'Integer', '(no default value)', 'MASKABLE'),
  (7, 'graph', 'graph.allow-stale-config', 'Whether to allow the local and storage-backend-hosted copies of the configuration to contain conflic', 'Boolean', 'true', 'MASKABLE'),
  (8, 'graph', 'graph.graphname', 'This config option is an optional configuration setting that you may supply when opening a graph. Th', 'String', '(no default value)', 'LOCAL'),
  (9, 'graph', 'graph.set-vertex-id', 'Whether user provided vertex ids should be enabled and JanusGraph’s automatic id allocation be disab', 'Boolean', 'false', 'FIXED'),
  (10, 'graph', 'graph.unique-instance-id-suffix', 'When this is set and unique-instance-id is not, this JanusGraph instance’s unique identifier is gene', 'Short', '(no default value)', 'LOCAL'),
  (11, 'ids', 'ids.block-size', 'Globally reserve graph element IDs in chunks of this size. Setting this too low will make commits fr', 'Integer', '10000', 'GLOBAL_OFFLINE'),
  (12, 'ids', 'ids.flush', 'When true, vertices and edges are assigned IDs immediately upon creation. When false, IDs are assign', 'Boolean', 'true', 'MASKABLE'),
  (13, 'ids', 'ids.num-partitions', 'Number of partition block to allocate for placement of vertices', 'Integer', '10', 'MASKABLE'),
  (14, 'ids', 'ids.placement', 'Name of the vertex placement strategy or full class name', 'String', 'simple', 'MASKABLE'),
  (15, 'ids', 'ids.renew-percentage', 'When the most-recently-reserved ID block has only this percentage of its total IDs remaining (expres', 'Double', '0.3', 'MASKABLE'),
  (16, 'ids', 'ids.renew-timeout', 'The number of milliseconds that the JanusGraph id pool manager will wait before giving up on allocat', 'Duration', '120000 ms', 'MASKABLE'),
  (17, 'ids', 'ids.store-name', 'The name of the ID KCVStore. IDS_STORE_NAME is meant to be used only for backward compatibility with', 'String', 'janusgraph_ids', 'GLOBAL_OFFLINE'),
  (18, 'graph', 'graph.timestamps', 'The timestamp resolution to use when writing to storage and indices. Sets the time granularity for t', 'TimestampProviders', 'MICRO', 'FIXED'),
  (19, 'graph', 'graph.unique-instance-id', 'Unique identifier for this JanusGraph instance. This must be unique among all instances concurrently', 'String', '(no default value)', 'LOCAL'),
  (20, 'gremlin', 'gremlin.graph', 'The implementation of graph factory that will be used by gremlin server', 'String', 'org.janusgraph.core.JanusGraphFactory', 'LOCAL'),
  (21, 'computer', 'computer.result-mode', 'How the graph computer should return the computed results. persist for writing them into the graph, ', 'String', 'none', 'MASKABLE'),
  (22, 'cluster', 'cluster.max-partitions', 'The number of virtual partition blocks created in the partitioned graph. This should be larger than ', 'Integer', '32', 'FIXED'),
  (23, 'attributes.custom', 'attributes.custom.[X].serializer-class', 'Class of the custom attribute serializer to be registered', 'String', '(no default value)', 'GLOBAL_OFFLINE'),
  (24, 'attributes.custom', 'attributes.custom.[X].attribute-class', 'Class of the custom attribute to be registered', 'String', '(no default value)', 'GLOBAL_OFFLINE'),
  (25, 'ids.authority', 'ids.authority.conflict-avoidance-mode', 'This setting helps separate JanusGraph instances sharing a single graph storage backend avoid conten', 'ConflictAvoidanceMode', 'NONE ', 'GLOBAL_OFFLINE'),
  (26, 'ids.authority', 'ids.authority.conflict-avoidance-tag', 'Conflict avoidance tag to be used by this JanusGraph instance when allocating IDs', 'Integer', '0', 'LOCAL'),
  (27, 'ids.authority', 'ids.authority.conflict-avoidance-tag-bits', 'Configures the number of bits of JanusGraph-assigned element IDs that are reserved for the conflict ', 'Integer', '4', 'FIXED'),
  (28, 'ids.authority', 'ids.authority.randomized-conflict-avoidance-retries', 'Number of times the system attempts ID block reservations with random conflict avoidance tags before', 'Integer', '5', 'MASKABLE'),
  (29, 'ids.authority', 'ids.authority.wait-time', 'The number of milliseconds the system waits for an ID block reservation to be acknowledged by the st', 'Duration', '300 ms', 'GLOBAL_OFFLINE'),
  (30, 'index', 'index.[X].backend', 'The indexing backend used to extend and optimize JanusGraph’s query functionality. This setting is optional. JanusGraph can use multiple heterogeneous index backends. Hence, this option can appear more than once, so long as the user-defined name between "index" and "backend" is unique among appearances.Similar to the storage backend, this should be set to one of JanusGraph’s built-in shorthand names for its standard index backends (shorthands: lucene, elasticsearch, es, solr) or to the full package and classname of a custom/third-party IndexProvider implementation.', 'String', 'elasticsearch', 'GLOBAL_OFFLINE'),
  (31, 'index', 'index.[X].conf-file', 'Path to a configuration file for those indexing backends that require/support a separate config file', 'String', NULL, 'MASKABLE'),
  (32, 'index', 'index.[X].directory', 'Directory to store index data locally', 'String', NULL, 'MASKABLE'),
  (33, 'index', 'index.[X].hostname', 'The hostname or comma-separated list of hostnames of index backend servers. This is only applicable to some index backends, such as elasticsearch and solr.', 'String[]', '127.0.0.1', 'MASKABLE'),
  (34, 'index', 'index.[X].index-name', 'Name of the index if required by the indexing backend', 'String', 'janusgraph', 'GLOBAL_OFFLINE'),
  (35, 'index', 'index.[X].map-name', 'Whether to use the name of the property key as the field name in the index. It must be ensured, that theindexed property key names are valid field names. Renaming the property key will NOT rename the field and its the developers responsibility to avoid field collisions.', 'String', 'janusgraph', 'GLOBAL_OFFLINE'),
  (36, 'index', 'index.[X].max-result-set-size', 'Maxium number of results to return if no limit is specified. For index backends that support scrolling, it represents the number of results in each batch', 'Integer', '50', 'MASKABLE'),
  (37, 'index', 'index.[X].port', 'The port on which to connect to index backend servers', 'Integer', NULL, 'MASKABLE'),
  (38, 'index', 'index.[X].elasticsearch.bulk-refresh', 'Elasticsearch bulk API refresh setting used to control when changes made by this request are made vi', 'String', 'false', 'MASKABLE'),
  (39, 'index', 'index.[X].elasticsearch.health-request-timeout', 'When JanusGraph initializes its ES backend, JanusGraph waits up to this duration for the ES cluster ', 'String', '30s', 'MASKABLE'),
  (40, 'index', 'index.[X].elasticsearch.interface', 'Interface for connecting to Elasticsearch. TRANSPORT_CLIENT and NODE were previously supported, but ', 'String', 'REST_CLIENT', 'MASKABLE'),
  (41, 'index', 'index.[X].elasticsearch.scroll-keep-alive', 'How long (in secondes) elasticsearch should keep alive the scroll context.', 'Integer', '60', 'GLOBAL_OFFLINE'),
  (42, 'index', 'index.[X].elasticsearch.use-all-field', 'Whether JanusGraph should add an "all" field mapping. When enabled field mappings will include a "copy_to" parameter referencing the "all" field. This is supported since Elasticsearch 6.x and is required when using wildcard fields starting in Elasticsearch 6.x.', 'Boolean', 'true', 'GLOBAL_OFFLINE'),
  (43, 'index', 'index.[X].elasticsearch.use-deprecated-multitype-index', 'Whether JanusGraph should group these indices into a single Elasticsearch index (requires Elasticsearch 5.x or earlier).', 'Boolean', 'false', 'GLOBAL_OFFLINE'),
  (44, 'index', 'index.[X].elasticsearch.create.sleep', 'How long to sleep, in milliseconds, between the successful completion of a (blocking) index creation request and the first use of that index. This only applies when creating an index in ES, which typically only happens the first time JanusGraph is started on top of ES. If the index JanusGraph is configured to use already exists, then this setting has no effect', 'Long', '200', 'MASKABLE'),
  (45, 'index', 'index.[X].elasticsearch.create.use-external-mappings', 'Whether JanusGraph should make use of an external mapping when registering an index.', 'Boolean', 'false', 'MASKABLE'),
  (46, 'index', 'index.[X].solr.configset', 'If specified, the same solr configSet can be resued for each new Collection that is created in SolrCloud', 'String', '(no default value)', 'MASKABLE'),
  (47, 'index', 'index.[X].solr.dyn-fields', 'Whether to use dynamic fields (which appends the data type to the field name). If dynamic fields is disabledthe user must map field names and define them explicitly in the schema', 'Boolean', 'true', 'GLOBAL_OFFLINE'),
  (48, 'index', 'index.[X].solr.http-compression', 'Enable/disable compression on the HTTP connections made to Solr.', 'Boolean', 'false', 'MASKABLE'),
  (49, 'index', 'index.[X].solr.http-connection-timeout', 'Solr HTTP connection timeout.', 'Integer', '5000', 'MASKABLE'),
  (50, 'index', 'index.[X].solr.http-max', 'Maximum number of HTTP connections in total to all Solr servers.', 'Integer', '100', 'MASKABLE'),
  (51, 'index', 'index.[X].solr.http-max-per-host', 'Maximum number of HTTP connections per Solr host.', 'Integer', '20', 'MASKABLE'),
  (52, 'index', 'index.[X].solr.http-urls', 'List of URLs to use to connect to Solr Servers (LBHttpSolrClient is used), don’t add core or collection name to the URL', 'String[]', 'http://localhost:8983/solr', 'MASKABLE'),
  (53, 'index', 'index.[X].solr.key-field-names', 'Field name that uniquely identifies each document in Solr. Must be specified as a list of collection=field', 'String[]', '(no default value)', 'GLOBAL'),
  (54, 'index', 'index.[X].solr.max-shards-per-node', 'Maximum number of shards per node. This applies when creating a new collection which is only supported under the SolrCloud operation mode', 'Integer', '1', 'GLOBAL_OFFLINE'),
  (55, 'index', 'index.[X].solr.mode', 'The operation mode for Solr which is either via HTTP (http) or using SolrCloud (cloud)', 'String', 'cloud', 'GLOBAL_OFFLINE'),
  (56, 'index', 'index.[X].solr.num-shards', 'Number of shards for a collection. This applies when creating a new collection which is only supported under the SolrCloud operation mode', 'Integer', '1', 'GLOBAL_OFFLINE'),
  (57, 'index', 'index.[X].solr.replication-factor', 'Replication factor for a collection. This applies when creating a new collection which is only supported under the SolrCloud operation mode', 'Integer', '1', 'GLOBAL_OFFLINE'),
  (58, 'index', 'index.[X].solr.ttl_field', 'Name of the TTL field for Solr collections.', 'String', 'ttl', 'GLOBAL_OFFLINE'),
  (59, 'index', 'index.[X].solr.wait-searcher', 'When mutating - wait for the index to reflect new mutations before returning. This can have a negati', 'Boolean', 'false', 'LOCAL'),
  (60, 'index', 'index.[X].solr.zookeeper-url', 'URL of the Zookeeper instance coordinating the SolrCloud cluster', 'String', 'localhost:2181', 'MASKABLE'),
  (61, 'index', '', 'URL of the Zookeeper instance coordinating the SolrCloud cluster', 'String', 'localhost:2181	', 'MASKABLE'),
  (62, 'log', 'log.[X].backend', 'Define the log backed to use', 'String', NULL, 'GLOBAL_OFFLINE'),
  (63, 'log', 'log.[X].fixed-partition', 'Whether all log entries are written to one fixed partition even if the backend store is partitioned.This can cause imbalanced loads and should only be used on low volume logs', 'Boolean', 'false', 'GLOBAL_OFFLINE'),
  (64, 'log', 'log.[X].key-consistent', 'Whether to require consistency for log reading and writing messages to the storage backend', 'Boolean', 'false', 'MASKABLE'),
  (65, 'log', 'log.[X].max-partitions', 'The maximum number of partitions to use for logging. Setting up this many actual or virtual partitions. Must be bigger than 0and a power of 2', 'Integer', '(no default value)', 'FIXED'),
  (66, 'log', 'log.[X].max-read-time', 'Maximum time in ms to try reading log messages from the backend before failing.', 'Duration', '4000 ms', 'MASKABLE'),
  (67, 'log', 'log.[X].max-write-time', 'Maximum time in ms to try persisting log messages against the backend before failing.', 'Duration', '10000 ms', 'MASKABLE'),
  (68, 'log', 'log.[X].num-buckets', 'The number of buckets to split log entries into for load balancing', 'Integer', '1', 'GLOBAL_OFFLINE'),
  (69, 'log', 'log.[X].read-batch-size', 'Maximum number of log messages to read at a time for logging implementations that read messages in batches', 'Integer', '1024', 'MASKABLE'),
  (70, 'log', 'log.[X].read-interval', 'Time in ms between message readings from the backend for this logging implementations that read message in batch', 'Duration', '5000 ms', 'MASKABLE'),
  (71, 'log', 'log.[X].read-lag-time', 'Maximum time in ms that it may take for reads to appear in the backend. If a write does not becomevisible in the storage backend in this amount of time, a log reader might miss the message', 'Duration', '500 ms', 'MASKABLE'),
  (72, 'log', 'log.[X].read-threads', 'Number of threads to be used in reading and processing log messages', 'Integer', '1', 'MASKABLE'),
  (73, 'log', 'log.[X].send-batch-size', 'Maximum number of log messages to batch up for sending for logging implementations that support batch sending', 'Integer', '256', 'MASKABLE'),
  (74, 'log', 'log.[X].send-delay', 'Maximum time in ms that messages can be buffered locally before sending in batch', 'Duration', '1000 ms', 'MASKABLE'),
  (75, 'log', 'log.[X].ttl', 'Sets a TTL on all log entries, meaningthat all entries added to this log expire after the configured amount of time. Requiresthat the log implementation supports TTL', 'Duration', '(no default value)', 'GLOBAL'),
  (76, 'metrics', 'metrics.enabled', 'Whether to enable basic timing and operation count monitoring on backend', 'Boolean', 'false', 'MASKABLE'),
  (77, 'metrics', 'metrics.merge-stores', 'Whether to aggregate measurements for the edge store, vertex index, edge index, and ID store', 'Boolean', 'true', 'MASKABLE'),
  (78, 'metrics', 'metrics.prefix', 'The default name prefix for Metrics reported by JanusGraph.', 'String', 'org.janusgraph', 'MASKABLE'),
  (79, 'metrics.console', 'metrics.console.interval', 'Time between Metrics reports printing to the console, in milliseconds', 'Duration', '(no default value)', 'MASKABLE'),
  (80, 'metrics.csv', 'metrics.csv.directory', 'Metrics CSV output directory', 'String', '(no default value)', 'MASKABLE'),
  (81, 'metrics.csv', 'metrics.csv.interval', 'Time between dumps of CSV files containing Metrics data, in milliseconds', 'Duration', '(no default value)', 'MASKABLE'),
  (82, 'metrics.ganglia', 'metrics.ganglia.addressing-mode', 'Whether to communicate to Ganglia via uni- or multicast', 'String', 'unicast', 'MASKABLE'),
  (83, 'metrics.ganglia', 'metrics.ganglia.hostname', 'The unicast host or multicast group name to which Metrics will send Ganglia data', 'String', '(no default value)', 'MASKABLE'),
  (84, 'metrics.ganglia', 'metrics.ganglia.interval', 'The number of milliseconds to wait between sending Metrics data to Ganglia', 'Duration', '(no default value)', 'MASKABLE'),
  (85, 'metrics.ganglia', 'metrics.ganglia.port', 'The port to which Ganglia data are sent', 'Integer', '8649', 'MASKABLE'),
  (86, 'metrics.ganglia', 'metrics.ganglia.protocol-31', 'Whether to send data to Ganglia in the 3.1 protocol format', 'Boolean', 'true', 'MASKABLE'),
  (87, 'metrics.ganglia', 'metrics.ganglia.spoof', 'If non-null, it must be a valid Gmetric spoof string formatted as an IP:hostname pair. See https://github.com/ganglia/monitor-core/wiki/Gmetric-Spoofing for information about this setting', 'String', '(no default value)', 'MASKABLE'),
  (88, 'metrics.ganglia', 'metrics.ganglia.ttl', 'The multicast TTL to set on outgoing Ganglia datagrams', 'Integer', '1', 'MASKABLE'),
  (89, 'metrics.ganglia', 'metrics.ganglia.uuid', 'The host UUID to set on outgoing Ganglia datagrams. See https://github.com/ganglia/monitor-core/wiki/UUIDSources for information about this setting', 'String', '(no default value)', 'LOCAL'),
  (90, 'metrics.graphite', 'metrics.graphite.hostname', 'The hostname to receive Graphite plaintext protocol metric data', 'String', '(no default value)', 'MASKABLE'),
  (91, 'metrics.graphite', 'metrics.graphite.interval', 'The number of milliseconds to wait between sending Metrics data', 'Duration', '(no default value)', 'MASKABLE'),
  (92, 'metrics.graphite', 'metrics.graphite.port', 'The port to which Graphite data are sent', 'Integer', '2003', 'MASKABLE'),
  (93, 'metrics.graphite', 'metrics.graphite.prefix', 'A Graphite-specific prefix for reported metrics', 'String', '(no default value)', 'MASKABLE'),
  (94, 'metrics.jmx', 'metrics.jmx.agentid', 'The JMX agentId used by Metrics', 'String', '(no default value)', 'MASKABLE'),
  (95, 'metrics.jmx', 'metrics.jmx.domain', 'The JMX domain in which to report Metrics', 'String', '(no default value)', 'MASKABLE'),
  (96, 'metrics.jmx', 'metrics.jmx.enabled', 'Whether to report Metrics through a JMX MBean', 'Boolean', 'false', 'MASKABLE'),
  (97, 'metrics.slf4j', 'metrics.slf4j.interval', 'Time between slf4j logging reports of Metrics data, in milliseconds', 'Duration', '(no default value)', 'MASKABLE'),
  (98, 'metrics.slf4j', 'metrics.slf4j.logger', 'The complete name of the Logger through which Metrics will report via Slf4j', 'String', '(no default value)', 'MASKABLE'),
  (99, 'query', 'query.batch', 'Whether traversal queries should be batched when executed against the storage backend. This can lead to significant performance improvement if there is a non-trivial latency to the backend.', 'Boolean', 'false', 'MASKABLE'),
  (100, 'query', 'query.fast-property', 'Whether to pre-fetch all properties on first singular vertex property access. This can eliminate backend calls on subsequentproperty access for the same vertex at the expense of retrieving all properties at once. This can be expensive for vertices with many properties', 'Boolean', 'true', 'MASKABLE'),
  (101, 'query', 'query.force-index', 'Whether JanusGraph should throw an exception if a graph query cannot be answered using an index. Doing solimits the functionality of JanusGraph’s graph queries but ensures that slow graph queries are avoided on large graphs. Recommended for production use of JanusGraph', 'Boolean', 'false', 'MASKABLE'),
  (102, 'query', 'query.ignore-unknown-index-key', 'Whether to ignore undefined types encountered in user-provided index queries', 'Boolean', 'false', 'MASKABLE'),
  (103, 'query', 'query.smart-limit', 'Whether the query optimizer should try to guess a smart limit for the query to ensure responsiveness in light of possibly large result sets. Those will be loaded incrementally if this option is enabled', 'Boolean', 'true', 'MASKABLE'),
  (104, 'schema', 'schema.default', 'Configures the DefaultSchemaMaker to be used by this graph. If set to none, automatic schema creation is disabled. Defaults to a blueprints compatible schema maker with MULTI edge labels and SINGLE property keys', 'String', NULL, 'MASKABLE'),
  (105, 'storage', 'storage.backend', 'The primary persistence provider used by JanusGraph. This is required. It should be set one of JanusGraph’s built-in shorthand names for its standard storage backends (shorthands: berkeleyje, cassandrathrift, cassandra, astyanax, embeddedcassandra, cql, hbase, inmemory) or to the full package and classname of a custom/third-party StoreManager implementation.', 'String', '(no default value)', 'LOCAL'),
  (106, 'storage', 'storage.batch-loading', 'Whether to enable batch loading into the storage backend', 'Boolean', 'false', 'LOCAL'),
  (107, 'storage', 'storage.buffer-size', 'Size of the batch in which mutations are persisted', 'Integer', '1024', 'MASKABLE'),
  (108, 'storage', 'storage.conf-file', 'Path to a configuration file for those storage backends which require/support a single separate config file.', 'String', '(no default value)', 'LOCAL'),
  (109, 'storage', 'storage.connection-timeout', 'Default timeout, in milliseconds, when connecting to a remote database instance', 'Duration', '10000 ms', 'MASKABLE'),
  (110, 'storage', 'storage.directory', 'Storage directory for those storage backends that require local storage.', 'String', '(no default value)', 'LOCAL'),
  (111, 'storage', 'storage.drop-on-clear', 'Whether to drop the graph database (true) or delete rows (false) when clearing storage. Note that some backends always drop the graph database when clearing storage. Also note that indices are always dropped when clearing storage', 'Boolean', 'true', 'MASKABLE'),
  (112, 'storage', 'storage.hostname', 'The hostname or comma-separated list of hostnames of storage backend servers. This is only applicabl', 'String[]', '127.0.0.1', 'LOCAL'),
  (113, 'storage', 'storage.page-size', 'JanusGraph break requests that may return many results from distributed storage backends into a series of requests for small chunks/pages of results, where each chunk contains up to this many elements', 'Integer', '100', 'MASKABLE'),
  (114, 'storage', 'storage.parallel-backend-ops', 'Whether JanusGraph should attempt to parallelize storage operations', 'Boolean', 'true', 'MASKABLE'),
  (115, 'storage', 'storage.password', 'Password to authenticate against backend', 'String', '(no default value)', 'LOCAL'),
  (116, 'storage', 'storage.port', 'The port on which to connect to storage backend servers.', 'Integer', '(no default value)', 'LOCAL'),
  (117, 'storage', 'storage.read-only', 'Read-only database', 'Boolean', 'false', 'LOCAL'),
  (118, 'storage', 'storage.read-time', 'Maximum time (in ms) to wait for a backend read operation to complete successfully. If a backend read operationfails temporarily, JanusGraph will backoff exponentially and retry the operation until the wait time has been exhausted', 'Duration', '10000 ms', 'MASKABLE'),
  (119, 'storage', 'storage.root', 'Storage root directory for those storage backends that require local storage. If you do not supply storage.directory and you do supply graph.graphname, then your data will be stored in the directory equivalent to <STORAGE_ROOT>/<GRAPH_NAME>', 'String', '(no default value)', 'LOCAL'),
  (120, 'storage', 'storage.setup-wait', 'Time in milliseconds for backend manager to wait for the storage backends to become available when J', 'Duration', '60000 ms', 'MASKABLE'),
  (121, 'storage', 'storage.transactions', 'Enables transactions on storage backends that support them', 'Boolean', 'true', 'MASKABLE'),
  (122, 'storage', 'storage.username', 'Username to authenticate against backend', 'String', '(no default value)', 'LOCAL'),
  (123, 'storage', 'storage.write-time', 'Maximum time (in ms) to wait for a backend write operation to complete successfully. If a backend wr', 'Duration', '100000 ms', 'MASKABLE'),
  (124, 'storage.berkeleyje', 'storage.berkeleyje.cache-percentage', 'Percentage of JVM heap reserved for BerkeleyJE’s cache', 'Integer', '65', 'MASKABLE'),
  (125, 'storage.berkeleyje', 'storage.berkeleyje.isolation-level', 'The isolation level used by transactions', 'String', 'REPEATABLE_READ', 'MASKABLE'),
  (126, 'storage.berkeleyje', 'storage.berkeleyje.lock-mode', 'The BDB record lock mode used for read operations', 'String', 'LockMode.DEFAULT', 'MASKABLE'),
  (127, 'storage.cassandra', 'storage.cassandra.atomic-batch-mutate', 'True to use Cassandra atomic batch mutation, false to use non-atomic batches', 'Boolean', 'true', 'MASKABLE'),
  (128, 'storage.cassandra', 'storage.cassandra.compaction-strategy-class', 'The compaction strategy to use for JanusGraph tables', 'String', '(no default value)', 'FIXED'),
  (129, 'storage.cassandra', 'storage.cassandra.compaction-strategy-options', 'Compaction strategy options. This list is interpreted as a map. It must have an even number of eleme', 'String[]', '(no default value)', 'FIXED'),
  (130, 'storage.cassandra', 'storage.cassandra.compression', 'Whether the storage backend should use compression when storing the data', 'Boolean', 'true', 'FIXED'),
  (131, 'storage.cassandra', 'storage.cassandra.compression-block-size', 'The size of the compression blocks in kilobytes', 'Integer', '64', 'FIXED'),
  (132, 'storage.cassandra', 'storage.cassandra.compression-type', 'The sstable_compression value JanusGraph uses when creating column families. This accepts any value ', 'String', 'LZ4Compressor', 'MASKABLE'),
  (133, 'storage.cassandra', 'storage.cassandra.frame-size-mb', 'The thrift frame size in megabytes', 'Integer', '15', 'MASKABLE'),
  (134, 'storage.cassandra', 'storage.cassandra.keyspace', 'The name of JanusGraph’s keyspace. It will be created if it does not exist. If it is not supplied, b', 'String', 'janusgraph', 'LOCAL'),
  (135, 'storage.cassandra', 'storage.cassandra.read-consistency-level', 'The consistency level of read operations against Cassandra', 'String', 'QUORUM', 'MASKABLE'),
  (136, 'storage.cassandra', 'storage.cassandra.replication-factor', 'The number of data replicas (including the original copy) that should be kept. This is only meaningf', 'Integer', '1', 'GLOBAL_OFFLINE'),
  (137, 'storage.cassandra', 'storage.cassandra.replication-strategy-class', 'The replication strategy to use for JanusGraph keyspace', 'String', 'org.apache.cassandra.locator.SimpleStrategy', 'FIXED'),
  (138, 'storage.cassandra', 'storage.cassandra.replication-strategy-options', 'Replication strategy options, e.g. factor or replicas per datacenter. This list is interpreted as a ', 'String[]', '(no default value)', 'FIXED'),
  (139, 'storage.cassandra', 'storage.cassandra.write-consistency-level', 'The consistency level of write operations against Cassandra', 'String', 'QUORUM', 'MASKABLE'),
  (140, 'storage.cassandra.astyanax', 'storage.cassandra.astyanax.cluster-name', 'Default name for the Cassandra cluster', 'String', 'JanusGraph Cluster', 'MASKABLE'),
  (141, 'storage.cassandra.astyanax', 'storage.cassandra.astyanax.connection-pool-type', 'Astyanax’s connection pooler implementation', 'String', 'TOKEN_AWARE', 'MASKABLE'),
  (142, 'storage.cassandra.astyanax', 'storage.cassandra.astyanax.frame-size', 'The thrift frame size in mega bytes', 'Integer', '15', 'MASKABLE'),
  (143, 'storage.cassandra.astyanax', 'storage.cassandra.astyanax.host-supplier', 'Host supplier to use when discovery type is set to DISCOVERY_SERVICE or TOKEN_AWARE', 'String', '(no default value)', 'MASKABLE'),
  (144, 'storage.cassandra.astyanax', 'storage.cassandra.astyanax.local-datacenter', 'The name of the local or closest Cassandra datacenter. When set and not whitespace, this value will be passed into ConnectionPoolConfigurationImpl.setLocalDatacenter. When unset or set to whitespace, setLocalDatacenter will not be invoked', 'String', '(no default value)', 'MASKABLE'),
  (145, 'storage.cassandra.astyanax', 'storage.cassandra.astyanax.max-cluster-connections-per-host', 'Maximum pooled \"cluster\" connections per host', 'Integer', '3', 'MASKABLE'),
  (146, 'storage.cassandra.astyanax', 'storage.cassandra.astyanax.max-connections', 'Maximum open connections allowed in the pool (counting all hosts)', 'Integer', '-1', 'MASKABLE'),
  (147, 'storage.cassandra.astyanax', 'storage.cassandra.astyanax.max-connections-per-host', 'Maximum pooled connections per host', 'Integer', '32', 'MASKABLE'),
  (148, 'storage.cassandra.astyanax', 'storage.cassandra.astyanax.max-operations-per-connection', 'Maximum number of operations allowed per connection before the connection is closed', 'Integer', '100000', 'MASKABLE'),
  (149, 'storage.cassandra.astyanax', 'storage.cassandra.astyanax.node-discovery-type', 'How Astyanax discovers Cassandra cluster nodes', 'String', 'RING_DESCRIBE', 'MASKABLE'),
  (150, 'storage.cassandra.astyanax', 'storage.cassandra.astyanax.read-page-size', 'The page size for Cassandra read operations', 'Integer', '4096', 'MASKABLE'),
  (151, 'storage.cassandra.astyanax', 'storage.cassandra.astyanax.retry-backoff-strategy', 'Astyanax’s retry backoff strategy with configuration parameters', 'String', 'com.netflix.astyanax.connectionpool.impl.FixedRetryBackoffStrategy,1000,5000', 'MASKABLE'),
  (152, 'storage.cassandra.astyanax', 'storage.cassandra.astyanax.retry-delay-slice', 'Astyanax’s connection pool \"retryDelaySlice\" parameter', 'Integer', '10000', 'MASKABLE'),
  (153, 'storage.cassandra.astyanax', 'storage.cassandra.astyanax.retry-max-delay-slice', 'Astyanax’s connection pool \"retryMaxDelaySlice\" parameter', 'Integer', '10', 'MASKABLE'),
  (154, 'storage.cassandra.astyanax', 'storage.cassandra.astyanax.retry-policy', 'Astyanax’s retry policy implementation with configuration parameters', 'String', 'com.netflix.astyanax.retry.BoundedExponentialBackoff,100,25000,8', 'MASKABLE'),
  (155, 'storage.cassandra.astyanax', 'storage.cassandra.astyanax.retry-suspend-window', 'Astyanax’s connection pool \"retryMaxDelaySlice\" parameter', 'Integer', '20000', 'MASKABLE'),
  (156, 'storage.cassandra.ssl', 'storage.cassandra.ssl.enabled', 'Controls use of the SSL connection to Cassandra', 'Boolean', 'false', 'LOCAL'),
  (157, 'storage.cassandra.ssl.truststore', 'storage.cassandra.ssl.truststore.location', 'Marks the location of the SSL Truststore.', 'String', NULL, 'LOCAL'),
  (158, 'storage.cassandra.ssl.truststore', 'storage.cassandra.ssl.truststore.password', 'The password to access SSL Truststore.', 'String', NULL, 'LOCAL'),
  (159, 'storage.cassandra.thrift.cpool', 'storage.cassandra.thrift.cpool.evictor-period', 'Approximate number of milliseconds between runs of the idle connection evictor. Set to -1 to never run the idle connection evictor.', 'Long', '30000', 'MASKABLE'),
  (160, 'storage.cassandra.thrift.cpool', 'storage.cassandra.thrift.cpool.idle-test', 'Whether the idle connection evictor validates idle connections and drops those that fail to validate', 'Boolean', 'false', 'MASKABLE'),
  (161, 'storage.cassandra.thrift.cpool', 'storage.cassandra.thrift.cpool.idle-tests-per-eviction-run', 'When the value is negative, e.g. -n, roughly one nth of the idle connections are tested per run. When the value is positive, e.g. n, the min(idle-count, n) connections are tested per run', 'Integer', '0', 'MASKABLE'),
  (162, 'storage.cassandra.thrift.cpool', 'storage.cassandra.thrift.cpool.max-active', 'Maximum number of concurrently in-use connections (-1 to leave undefined)', 'Integer', '16', 'MASKABLE'),
  (163, 'storage.cassandra.thrift.cpool', 'storage.cassandra.thrift.cpool.max-idle', 'Maximum number of concurrently idle connections (-1 to leave undefined)', 'Maximum number of concurrently idle connections (-1 to leave undefined)', '4', 'MASKABLE'),
  (164, 'storage.cassandra.thrift.cpool', 'storage.cassandra.thrift.cpool.max-total', 'Max number of allowed Thrift connections, idle or active (-1 to leave undefined)', 'Integer', '-1', 'MASKABLE'),
  (165, 'storage.cassandra.thrift.cpool', 'storage.cassandra.thrift.cpool.max-wait', 'Maximum number of milliseconds to block when storage.cassandra.thrift.cpool.when-exhausted is set to', 'Long', '-1', 'MASKABLE'),
  (166, 'storage.cassandra.thrift.cpool', 'storage.cassandra.thrift.cpool.min-evictable-idle-time', 'Minimum number of milliseconds a connection must be idle before it is eligible for eviction. See als', 'Long', '60000', 'MASKABLE'),
  (167, 'storage.cassandra.thrift.cpool', 'storage.cassandra.thrift.cpool.min-idle', 'Minimum number of idle connections the pool attempts to maintain', 'Integer', '0', 'MASKABLE'),
  (168, 'storage.cassandra.thrift.cpool', 'storage.cassandra.thrift.cpool.when-exhausted', 'What to do when clients concurrently request more active connections than are allowed by the pool. T', 'String', 'BLOCK', 'MASKABLE'),
  (169, 'storage.cql', 'storage.cql.atomic-batch-mutate', 'True to use Cassandra atomic batch mutation, false to use non-atomic batches', 'Boolean', 'false', 'MASKABLE'),
  (170, 'storage.cql', 'storage.cql.batch-statement-size', 'The number of statements in each batch', 'Integer', '20', 'MASKABLE'),
  (171, 'storage.cql', 'storage.cql.cluster-name', 'Default name for the Cassandra cluster', 'String', 'JanusGraph Cluster', 'MASKABLE'),
  (172, 'storage.cql', 'storage.cql.compaction-strategy-class', 'The compaction strategy to use for JanusGraph tables', 'String', '(no default value)', 'FIXED'),
  (173, 'storage.cql', 'storage.cql.compaction-strategy-options', 'Compaction strategy options. This list is interpreted as a map. It must have an even number of eleme', 'String[]\r\n\r\n', '(no default value)', 'FIXED'),
  (174, 'storage.cql', 'storage.cql.compression', 'Whether the storage backend should use compression when storing the data', 'Boolean', 'true', 'FIXED'),
  (175, 'storage.cql', 'storage.cql.compression-block-size', 'The size of the compression blocks in kilobytes', 'Integer', '64', 'FIXED'),
  (176, 'storage.cql', 'storage.cql.compression-type', 'The sstable_compression value JanusGraph uses when creating column families. This accepts any value ', 'String', 'LZ4Compressor', 'MASKABLE'),
  (177, 'storage.cql', 'storage.cql.keyspace', 'The name of JanusGraph’s keyspace. It will be created if it does not exist.', 'String', 'janusgraph', 'LOCAL'),
  (178, 'storage.cql', 'storage.cql.local-datacenter', 'The name of the local or closest Cassandra datacenter. When set and not whitespace, this value will ', 'String', '(no default value)', 'MASKABLE'),
  (179, 'storage.cql', 'storage.cql.only-use-local-consistency-for-system-operations', 'True to prevent any system queries from using QUORUM consistency and always use LOCAL_QUORUM instead', 'Boolean', 'false', 'MASKABLE'),
  (180, 'storage.cql', 'storage.cql.protocol-version', 'The protocol version used to connect to the Cassandra database. If no value is supplied then the dri', 'Integer', '0', 'LOCAL'),
  (181, 'storage.cql', 'storage.cql.read-consistency-level', 'The consistency level of read operations against Cassandra', 'String', 'QUORUM', 'MASKABLE'),
  (182, 'storage.cql', 'storage.cql.replication-factor', 'The number of data replicas (including the original copy) that should be kept', 'Integer', '1', 'GLOBAL_OFFLINE'),
  (183, 'storage.cql', 'storage.cql.replication-strategy-class', 'The replication strategy to use for JanusGraph keyspace', 'String', 'SimpleStrategy', 'FIXED'),
  (184, 'storage.cql', 'storage.cql.replication-strategy-options', 'Replication strategy options, e.g. factor or replicas per datacenter. This list is interpreted as a ', 'String[]\r\n\r\n', '(no default value)', 'FIXED'),
  (185, 'storage.cql', 'storage.cql.write-consistency-level', 'The consistency level of write operations against Cassandra', 'String', 'QUORUM', 'MASKABLE'),
  (186, 'storage.cql.ssl', 'storage.cql.ssl.enabled', 'Controls use of the SSL connection to Cassandra', 'Boolean', 'false', 'LOCAL'),
  (187, 'storage.cql.ssl.truststore', 'storage.cql.ssl.truststore.location', 'Marks the location of the SSL Truststore.', 'String', NULL, 'LOCAL'),
  (188, 'storage.cql.ssl.truststore', 'storage.cql.ssl.truststore.password', 'The password to access SSL Truststore.', 'String', NULL, 'LOCAL'),
  (189, 'storage.hbase', 'storage.hbase.compat-class', 'The package and class name of the HBaseCompat implementation. HBaseCompat masks version-specific HBase API differences. When this option is unset, JanusGraph calls HBase’s VersionInfo.getVersion() and loads the matching compat class at runtime. Setting this option forces JanusGraph to instead reflectively load and instantiate the specified class', 'String', '(no default value)', 'MASKABLE'),
  (190, 'storage.hbase', 'storage.hbase.compression-algorithm', 'An HBase Compression.Algorithm enum string which will be applied to newly created column families. The compression algorithm must be installed and available on the HBase cluster. JanusGraph cannot install and configure new compression algorithms on the HBase cluster by itself', 'String', 'GZ', 'MASKABLE'),
  (191, 'storage.hbase', 'storage.hbase.region-count', 'The number of initial regions set when creating JanusGraph’s HBase table', 'Integer', '(no default value)', 'MASKABLE'),
  (192, 'storage.hbase', 'storage.hbase.regions-per-server', 'The number of regions per regionserver to set when creating JanusGraph’s HBase table', 'Integer', '(no default value)', 'MASKABLE'),
  (193, 'storage.hbase', 'storage.hbase.short-cf-names', 'Whether to shorten the names of JanusGraph’s column families to one-character mnemonics to conserve ', 'Boolean', 'true', 'FIXED'),
  (194, 'storage.hbase', 'storage.hbase.skip-schema-check', 'Assume that JanusGraph’s HBase table and column families already exist. When this is true, JanusGrap', 'Boolean', 'false', 'MASKABLE'),
  (195, 'storage.hbase', 'storage.hbase.table', 'The name of the table JanusGraph will use. When storage.hbase.skip-schema-check is false, JanusGraph', 'String', 'janusgraph', 'LOCAL'),
  (196, 'storage.lock', 'storage.lock.backend', 'Locker type to use', 'String', 'consistentkey', 'GLOBAL_OFFLINE'),
  (197, 'storage.lock', 'storage.lock.clean-expired', 'Whether to delete expired locks from the storage backend', 'Boolean', 'false', 'MASKABLE'),
  (198, 'storage.lock', 'storage.lock.expiry-time', 'Number of milliseconds after which a lock is considered to have expired. Lock applications that were not released are considered expired after this time and released. This value should be larger than the maximum time a transaction can take in order to guarantee that no correctly held applications are expired pre-maturely and as small as possible to avoid dead lock', 'Duration', '300000 ms', 'GLOBAL_OFFLINE'),
  (199, 'storage.lock', 'storage.lock.local-mediator-group',
   'This option determines the LocalLockMediator instance used for early detection of lock contention between concurrent JanusGraph graph instances within the same process which are connected to the same storage backend. JanusGraph instances that have the same value for this variable will attempt to discover lock contention among themselves in memory before proceeding with the general-case distributed locking code. JanusGraph generates an appropriate default value for this option at startup. Overridding the default is generally only useful in testing',
   'String', '(no default value)', 'LOCAL'),
  (200, 'storage.lock', 'storage.lock.retries',
   'Number of times the system attempts to acquire a lock before giving up and throwing an exception',
   'Integer', '3', 'MASKABLE'),
  (201, 'storage.lock', 'storage.lock.wait-time',
   'Number of milliseconds the system waits for a lock application to be acknowledged by the storage backend. Also, the time waited at the end of all lock applications before verifying that the applications were successful. This value should be a small multiple of the average consistent write time',
   'Duration', '100 ms', 'GLOBAL_OFFLINE'),
  (202, 'storage.meta', 'storage.meta.[X].timestamps',
   'Whether to include timestamps in retrieved entries for storage backends that automatically annotated entries with timestamps',
   'Boolean', 'false', 'GLOBAL'),
  (203, 'storage.meta', 'storage.meta.[X].ttl',
   'Whether to include ttl in retrieved entries for storage backends that support storage and retrieval of cell level TTL',
   'Boolean', 'false', 'GLOBAL'),
  (204, 'storage.meta', 'storage.meta.[X].visibility',
   'Whether to include visibility in retrieved entries for storage backends that support cell level visibility',
   'Boolean', 'true', 'GLOBAL'),
  (205, 'tx', 'tx.log-tx',
   'Whether transaction mutations should be logged to JanusGraph’s write-ahead transaction log which can be used for recovery of partially failed transactions',
   'Boolean', 'false', 'GLOBAL'),
  (206, 'tx', 'tx.max-commit-time',
   'Maximum time (in ms) that a transaction might take to commit against all backends. This is used by the distributed write-ahead log processing to determine when a transaction can be considered failed (i.e. after this time has elapsed).Must be longer than the maximum allowed write time',
   'Duration', '10000 ms', 'GLOBAL'),
  (207, 'tx', 'tx.recovery.verbose',
   'Whether the transaction recovery system should print recovered transactions and other activity to standard output',
   'Boolean', 'false', 'MASKABLE');